---
ansible_user                 : daniel.zaharchenk00
ansible_ssh_private_key_file : /home/daniel.zaharchenk00/.ssh/petProj
bucket_name                  : test_danylo_bucket
git_backup_name              : backup_gitlab_backup.tar
jenkins_backup_name          : jenkins-backup-latest.tar.gz

gcloud_access_key : !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66343764363932633739373037646539306333336436336439626338386439633162626536636138
          3963653031653737306163363338323430373131323133640a343835653138376662633063636365
          36636465323839316533623834353334386534633366623632323237613161393135643566386363
          3166623462373230350a363138313430643637326464653738323930373235353631383133633161
          34633134653634373665333865613064363531383337613735616661346166616337
gcloud_secret_key : !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36363438323364396631313536636161633231326565626338356430396234313964383536333637
          3563313431353032373466376364333734363436666266370a353464653466646634343165396231
          63343330323434623433633063333366363632383534356430346666633039386437656566626533
          6662633365303766620a316339633063616665376635323032326139316538373362353962343638
          65363862633539653666353066616361656432623436383531616430613838396166333930353837
          3930303862383634313430633334373432613166323662646639
git_url           : http://35.234.64.2/
...
